---

- include: configure_base_system.yml
  tags: osx_base_system

- include: install_ruby.yml
  tags: osx_install_ruby

- include: install_xcode.yml
  tags: osx_install_xcode

- include: install_homebrew.yml
  tags: osx_install_homebrew

- include_role:
    name: nodejs
  tags: osx_install_nodejs

- include: download_certs.yml
  tags: osx_download_certs

- include: cocoapods.yml
  tags: osx_cocoapods

- include_role:
    name: configure-buildfarm
    tasks_from: configure_buildfarm_node
  tags: osx_configure_buildfarm

- include: configure_buildfarm_proxy.yml
  tags: osx_configure_proxy
